### ISSUE TITLE
15) Essential packages ./scripts/pacman-new-mirrorlist.sh

### ISSUE THREAD

**Issue by tocsh1** [predmijat/realworlddevopscourse#6]
I have this error 

./scripts/pacman-new-mirrorlist.sh
cp: cannot stat '/etc/pacman.d/mirrorlist.pacnew': No such file or directory
sed: can't read /etc/pacman.d/mirrorlist.temp: No such file or directory
'/etc/pacman.d/mirrorlist.temp' does not exist.
rm: cannot remove '/etc/pacman.d/mirrorlist.temp': No such file or directory

**Comment by tocsh1** [comment]
Maybe there was no an update of mirrorlist ?

**Comment by predmijat** [comment]
I would assume so, yes.
Also, as noted in another issue, please use Udemy for support as I usually need to ask for additional information some of which is not for public. Thank you!
