### ISSUE TITLE
after-14-essentials-4-bridge br0 does not show even rebooting twice

### ISSUE THREAD

**Issue by tocsh1** [predmijat/realworlddevopscourse#7]
Hello
In this chapter after-14-essentials-4-bridge], I rebooted twice, once from the web interface and once from within vps and
ip a does not show br0.

The ansible-playbook setup.yml finished without error

----------------------------------------------------------
TASK [essentials : include_tasks] *********************************************************
included: /home/me/ansible/essentials/tasks/br0.yml for mydomain.org

TASK [essentials : netdev] ****************************************************************
ok: [mydomain.org]

TASK [essentials : network] ***************************************************************
ok: [mydomain.org]

PLAY RECAP ********************************************************************************
mydomain.org               : ok=18   changed=0    unreachable=0    failed=0    skipped=0
 rescued=0    ignored=0

Thank you

**Comment by predmijat** [comment]
Hello, please reach me via email or via Udemy messages for support. To save time, include additional information - did you use Arch Linux like in the course or you made some modifications and if yes, which ones. Thank you!
